{\rtf1\ansi\ansicpg1252\cocoartf2511
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 apiVersion: apps/v1\
kind: Deployment\
metadata:\
  name: nginx-consume\
spec:\
  selector:\
    matchLabels:\
      app: nginx-consume-label\
  template:\
    metadata:\
      labels:\
        app: nginx-consume-label\
    spec:\
      containers:\
        - name: nginx\
          image: nginx\
          env:\
            - name: ENV_VARIABLE_FIRST\
              valueFrom:\
                configMapKeyRef:\
                  name: configmap_first\
                  key: env_variable_first\
            - name: ENV_VARIABLE_SECOND\
              valueFrom:\
                secretKeyRef:\
                  name: secret_first\
                  key: env_variable_second\
          volumeMounts:\
            - mountPath: /config\
              name: volume-first\
            - mountPath: /secret\
              name: volume-second\
      volumes:\
        - name: volume-first\
          configMap:\
            name: configmap_second\
            items:\
              - key: first_key\
                path: /configuration/key_one\
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0
\cf0               - key: second_key\
                path: /configuration/key_two\
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0
\cf0         - name: volume-second\
          secret:\
            secretName: secret_second\
}