{\rtf1\ansi\ansicpg1252\cocoartf2511
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 apiVersion: apps/v1\
kind: Deployment\
metadata:\
  name: nginx-limit\
spec:\
  replicas: 2\
  selector:\
    matchLabels:\
      app: nginx-limit-label\
  template:\
    metadata:\
      labels:\
        app: nginx-limit-label\
    spec:\
      containers:\
        - name: nginx\
          image: nginx\
          resources:\
            limits:\
              memory: 512Mi\
            requests:\
              memory: 256Mi\
}